### ISSUE TITLE
Prompt the user whether to use lossless or "visually indistinguishable lossy" for JPEG to JXL conversions

### ISSUE THREAD

**Issue by nekohayo** [kylxbn/jxl-migrate#10]
For me, there are two usecases for batch conversions:
* photographic libraries of professional shots we have taken where we want to preserve things losslessly, in which case the default `-d 0` cjxl encoding setting makes sense
* huge photos that are of lesser importance (ex: vacation photos, albums that others have sent to us, etc.) where filesize reduction is more important than imperceptible visual losses

With some test folder with 75 JPEGs from someone else's DSLR (a Nikon D80) where every JPEG image was easily weighing 10 MB each, the script's default lossless conversion behavior only saved 16% in filesizes. However, as soon as I hacked in `ret = convert(fullpath, lossy=True) ` in the JPEG section of this script, and re-ran my test batch encoding, this time it saved a whopping 83%! Going from 600 MB to 100 MB is much more impressive than going from 600 MB to 500 MB.

The thing is, this is a choice the user will probably have to make on a per-folder basis, because one album may be important to keep losselss whereas some other may be "just squeeze the hell out of it to reclaim disk space", and needing to hack the script before every run would be error-prone, so ideally, the script should prompt the user with a "y/N" kind of choice, after having received the path and detected that there are some ".jpg" or ".jpeg" files in the folder.

**Comment by kylxbn** [comment]
Thanks for the suggestion, now implemented with PR #11 !
