### ISSUE TITLE
Removing originals should be an option/parameter, off by default, to allow visual comparison?

### ISSUE THREAD

**Issue by nekohayo** [kylxbn/jxl-migrate#8]
To make it a bit less scary for people trying out such conversions, wouldn't it be better to default to the safest behavior of keeping the originals around unless a `--delete` parameter is passed? That way users can compare the before/after, ensure that color profiles, EXIF (and whatever else might matter) is successfully preserved?

**Comment by kylxbn** [comment]
Thanks for the suggestion, now implemented with PR #11 !
